export const dataEnTranslation = {
  data: {
    projects: {
      federationOfAutogeneratedGraphqlApis: {
        title: 'Federation of autogenerated GraphQL APIs',
        description:
          'A technology stack that allows an application to be split into several backends. Each backend has its own autogenerated database and CRUD Graphql API. All APIs are connected via a gateway into a single API.',
      },
      botFarm: {
        title: 'Bot farm',
        description:
            'System to efficiently manage over 30 computers and thousands of bot accounts. Complex automations created in the web application are processed by the server into simple commands and then executed by a worker application located on any Windows computer. Ability to remotely execute commands like: „open app, „move mouse to this point and click”, „type I am not a bot” on each PC connected to the server.  Provided the capability to create schedules and queue automations as tasks. Successfully developed and integrated multiple bots for various games. Implemented advanced logging functionalities to gather extensive information about the bots, surpassing the data collected by game developers. Created intuitive control panels for automation, device and bot management.'
      },
      windowsWorkerGraphQLAPI: {
        title: 'Windows Worker GraphQL API',
        description:
          'Control your computer remotely by calling GraphQL API. Mouse, keyboard, screen and process automation.',
      },
    },
  },
}
