export const dataPlTranslation = {
  data: {
    projects: {
      federationOfAutogeneratedGraphqlApis: {
        title: 'Federacja automatycznie generowanych GraphQL API',
        description:
          'Stack technologiczny umożliwiający podzielenie aplikacji na kilka backendów. Każdy backend posiada automatycznie wygenerowaną bazę danych i CRUD GraphQL API. Wszystkie endpointy są łączone za pomocą węzła w jedno API.',
      },
      botFarm: {
        title: 'Farma botów',
        description:
          'System do zarządzania ponad 30 komputerami i tysiącami kont botów. Skomplikowane automatyzacje stworzone w web aplikacji są przetwarzane przez serwer na proste polecenia i następnie wykonywane przez aplikację worker, znajdującą się na dowolnym komputerze z systemem Windows. Możliwość zdalnego wykonywania poleceń w stylu: "otwórz aplikację", "przesuń myszkę w to miejsce i kliknij", "napisz Nie jestem botem".  Możliwość tworzenia harmonogramów i kolejkowania różnych automatyzacji jako zadań. Wiele stworzonych i zintegrowanych botów do różnych gier. Zaawansowane logi, aby zbierać więcej informacji o botach niż sami twórcy gier. Różne panele do zarządzania automatyzacjami, urządzeniami i botami.',
      },
      windowsWorkerGraphQLAPI: {
        title: 'Windows Worker GraphQL API',
        description:
          'Zdalne sterowanie komputerem poprzez wywoływanie GraphQL API. Automatyzacja myszy, klawiatury, ekranu i procesów.',
      },
    },
  },
}
