import { Project } from 'shared/_types'

export const allProjects: Project[] = [
  {
    id: 'bot-farm',
    name: 'data.projects.botFarm.title',
    description: 'data.projects.botFarm.description',
    type: 'private',
    readMoreUrl: '/projects/bot-farm',
    imagesUrls: [
      '/projects/bot-farm/control-panel-devices.PNG',
      '/projects/bot-farm/control-panel-device.PNG',
      '/projects/bot-farm/accounts-submodules.PNG',
      '/projects/bot-farm/devices-submodules.PNG',
      '/projects/bot-farm/devices-schedules-form.PNG',
      '/projects/bot-farm/apps-submodules.PNG',
      '/projects/bot-farm/worker-submodules.PNG',
      '/projects/bot-farm/worker-activities-form-1.PNG',
      '/projects/bot-farm/worker-activities-form-2.PNG',
    ],
    technologiesNames: [
      'tsjs',
      'csharp',
      'python',
      'graphql',
      'nestjs',
      'nodejs',
      'prisma',
      'postgresql',
      'kafka',
      'apollo',
      'react',
      'nextjs',
      'chakraui',
      'mui',
      'playwright',
      'puppeteer',
      'nutjs',
      'jest',
      'docker',
      'prometheus',
      'grafana',
      'win32api',
      'gamehacking',
    ],
  },
  {
    id: 'autodoing',
    name: 'data.projects.autodoing.title',
    description: 'data.projects.autodoing.description',
    type: 'openSource',
    readMoreUrl: '/projects/autodoing',
    imagesUrls: ['/projects/autodoing/dashboard-example.jpg'],
    githubUrl: 'https://github.com/b0tf4th3r/autodoing',
    technologiesNames: ['tsjs', 'csharp', 'graphql', 'win32api', 'nestjs', 'nutjs', 'grafana', 'prometheus', 'docker'],
  },
]
