import {
  Technology,
  TechnologyGroup,
  TechnologyName,
} from 'shared/_types/technology'

import { Icon } from 'components/ui'

export const allTechnologies: Technology[] = [
  {
    name: 'tsjs',
    label: 'TypeScript / JavaScript',
    group: 'language',
    imageUrl: 'home/language/typescript.png',
  },
  {
    name: 'csharp',
    label: 'C#',
    group: 'language',
    imageUrl: 'home/language/csharp.png',
  },
  {
    name: 'python',
    label: 'Python',
    group: 'language',
    imageUrl: 'home/language/python.png',
  },
  {
    name: 'java',
    label: 'Java',
    group: 'language',
    imageUrl: 'home/language/java.png',
  },
  {
    name: 'graphql',
    label: 'GraphQL',
    group: 'language',
    imageUrl: 'home/language/graphql.png',
  },
  {
    name: 'nodejs',
    label: 'Node.js',
    group: 'backend',
    imageUrl: 'home/backend/nodejs.png',
  },
  {
    name: 'nestjs',
    label: 'NestJS',
    group: 'backend',
    imageUrl: 'home/backend/nestjs.png',
  },
  {
    name: 'apollo',
    label: 'Apollo',
    group: 'backend',
    imageUrl: 'home/backend/apollo.png',
  },
  {
    name: 'typegraphql',
    label: 'TypeGraphQL',
    group: 'backend',
    imageUrl: 'home/backend/typegraphql.png',
  },
  {
    name: 'prisma',
    label: 'Prisma',
    group: 'backend',
    imageUrl: 'home/backend/prisma.png',
  },
  {
    name: 'postgresql',
    label: 'PostgreSQL',
    group: 'backend',
    imageUrl: 'home/backend/postgresql.png',
  },
  {
    name: 'mysql',
    label: 'MySQL',
    group: 'backend',
    imageUrl: 'home/backend/mysql.png',
  },
  {
    name: 'kafka',
    label: 'Kafka',
    group: 'backend',
    imageUrl: 'home/backend/kafka.png',
  },
  {
    name: 'react',
    label: 'React',
    group: 'frontend',
    imageUrl: 'home/frontend/react.png',
  },
  {
    name: 'reactnative',
    label: 'React Native',
    group: 'frontend',
    imageUrl: 'home/frontend/react.png',
  },
  {
    name: 'nextjs',
    label: 'NextJS',
    group: 'frontend',
    imageUrl: 'home/frontend/nextjs.png',
  },
  {
    name: 'chakraui',
    label: 'Chakra UI',
    group: 'frontend',
    imageUrl: 'home/frontend/chakraui.png',
  },
  {
    name: 'mui',
    label: 'MUI',
    group: 'frontend',
    imageUrl: 'home/frontend/mui.png',
  },
  {
    name: 'styledcomponents',
    label: 'Styled Components',
    group: 'frontend',
    imageUrl: 'home/frontend/styledcomponents.png',
  },
  {
    name: 'sass',
    label: 'SASS',
    group: 'frontend',
    imageUrl: 'home/frontend/sass.png',
  },
  {
    name: 'playwright',
    label: 'Playwright',
    group: 'automation',
    imageUrl: 'home/automation/playwright.png',
  },
  {
    name: 'puppeteer',
    label: 'Puppeteer',
    group: 'automation',
    imageUrl: 'home/automation/puppeteer.png',
  },
  {
    name: 'scrapysplash',
    label: 'Scrapy / Splash',
    group: 'automation',
    imageUrl: 'home/automation/scrapy.png',
  },
  {
    name: 'nutjs',
    label: 'Nut.js',
    group: 'automation',
    imageUrl: 'home/automation/nutjs.png',
  },
  {
    name: 'docker',
    label: 'Docker',
    group: 'other',
    imageUrl: 'home/other/docker.png',
  },
  {
    name: 'git',
    label: 'Git',
    group: 'other',
    imageUrl: 'home/other/git.png',
  },
  {
    name: 'win32api',
    label: 'Win32 API',
    group: 'other',
    icon: <Icon name='win32api' size='30px' />,
  },
  {
    name: 'graylog',
    label: 'Graylog',
    group: 'other',
    imageUrl: 'home/other/graylog.png',
  },
  {
    name: 'memoryreadwrite',
    label: 'shared._Reading_and_writing_into_process_s_memory',
    group: 'other',
    icon: <Icon name='memoryreadwrite' size='30px' />,
  },
]

export const allTechnologiesNames: TechnologyName[] = [
  'apollo',
  'chakraui',
  'csharp',
  'docker',
  'git',
  'graphql',
  'graylog',
  'java',
  'kafka',
  'memoryreadwrite',
  'mui',
  'nestjs',
  'nextjs',
  'nodejs',
  'playwright',
  'postgresql',
  'mysql',
  'prisma',
  'puppeteer',
  'python',
  'react',
  'sass',
  'scrapysplash',
  'styledcomponents',
  'tsjs',
]

export const allTechnologiesGroups: TechnologyGroup[] = [
  'automation',
  'backend',
  'frontend',
  'language',
  'other',
]
